### PR TITLE
Task header

### PR DESCRIPTION
**Pull request by MIDAV0**

### CODE REVIEW

**Comment by rodrigopavezi** [comment]
@MIDAV0 looks good. I think it is best to move the `dataInitialStake` into the `useTaskData` hook. Also, rebase with main. I would suggest to merge my latest PR first. Let me know if you need help with that. Cheers

**Comment by MIDAV0** [comment]
@rodrigopavezi I will move `dataInitialStake` to `useTaskData` , but I need help with rebasing

**Comment by rodrigopavezi** [comment]
@MIDAV0 cool! Curious, what was changed on the main.bin?

**Comment by MIDAV0** [comment]
I don't know tbh, it changes automatically for some reason and I can't see what changes

**Comment by rodrigopavezi** [comment]
@MIDAV0 No problem!! we will replace it later anyway

**Review by rodrigopavezi — APPROVED** [review]
Looks good, let me fix the merging issue.

**Pull request merged**
